// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzgczvwrytyixuvdferj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6Z2N6dndyeXR5aXh1dmRmZXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTU2MzksImV4cCI6MjA3MjU3MTYzOX0.JdN0P7evHqECb0BJIynf2z5qTii01Uh0F1qUHsVhizs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});